#!/usr/bin/env node
/**
 * Generates sitemap.xml from the HTML files that actually exist on disk.
 *
 * The hand-maintained sitemap previously announced 6 blog posts to Google when
 * only 1 existed, so 5 URLs returned 404 to crawlers. Generating the file from
 * the filesystem makes that failure mode impossible.
 *
 * Usage: node tools/build-sitemap.mjs [--check]
 *   (no args)  rewrite sitemap.xml
 *   --check    exit 1 if sitemap.xml is out of date, without writing
 */
import { readdirSync, existsSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const BASE = 'https://charafatj.github.io/069digital/';

// Pages that must never be advertised to search engines.
const EXCLUDE = new Set(['test-services.html', '404.html']);

// Relative crawl priority. Anything not listed defaults to 0.5.
const PRIORITY = {
  '': '1.0',
  'services.html': '0.9',
  'leistungen/web-shop.html': '0.8',
  'leistungen/marke-design.html': '0.8',
  'leistungen/sichtbarkeit.html': '0.8',
  'leistungen/kontakt-buchung.html': '0.8',
  'blog.html': '0.7',
  'impressum.html': '0.3',
  'datenschutz.html': '0.3',
};

function htmlFiles() {
  const out = [];
  for (const f of readdirSync(ROOT)) {
    if (f.endsWith('.html') && !EXCLUDE.has(f)) out.push(f);
  }
  for (const dir of ['blog', 'leistungen']) {
    const d = join(ROOT, dir);
    if (!existsSync(d)) continue;
    for (const f of readdirSync(d)) {
      if (f.endsWith('.html') && !EXCLUDE.has(f)) out.push(dir + '/' + f);
    }
  }
  return out.sort();
}

function isNoindex(rel) {
  const src = readFileSync(join(ROOT, rel), 'utf8');
  return /<meta[^>]+name=["']robots["'][^>]*noindex/i.test(src);
}

function build() {
  const entries = [];
  for (const rel of htmlFiles()) {
    if (isNoindex(rel)) continue;
    // index.html is served at the directory root
    const loc = rel === 'index.html' ? '' : rel;
    const mtime = statSync(join(ROOT, rel)).mtime.toISOString().slice(0, 10);
    entries.push({ loc: BASE + loc, lastmod: mtime, priority: PRIORITY[loc] ?? '0.5' });
  }

  const body = entries
    .map(
      (e) =>
        `  <url>\n    <loc>${e.loc}</loc>\n    <lastmod>${e.lastmod}</lastmod>\n    <priority>${e.priority}</priority>\n  </url>`
    )
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by tools/build-sitemap.mjs — do not edit by hand -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;
}

const target = join(ROOT, 'sitemap.xml');
const next = build();
const check = process.argv.includes('--check');
const current = existsSync(target) ? readFileSync(target, 'utf8') : '';

// Compare ignoring lastmod, so a file touch alone is not a failure.
const strip = (s) => s.replace(/<lastmod>.*?<\/lastmod>/g, '');

if (check) {
  if (strip(current) !== strip(next)) {
    console.error('sitemap.xml is out of date. Run: node tools/build-sitemap.mjs');
    const urls = (s) => [...s.matchAll(/<loc>(.*?)<\/loc>/g)].map((m) => m[1]);
    const a = new Set(urls(current));
    const b = new Set(urls(next));
    [...a].filter((u) => !b.has(u)).forEach((u) => console.error('  stale (page does not exist): ' + u));
    [...b].filter((u) => !a.has(u)).forEach((u) => console.error('  missing (page exists): ' + u));
    process.exit(1);
  }
  console.log('sitemap.xml is up to date (' + [...next.matchAll(/<loc>/g)].length + ' urls)');
} else {
  writeFileSync(target, next);
  console.log('Wrote sitemap.xml with ' + [...next.matchAll(/<loc>/g)].length + ' urls:');
  [...next.matchAll(/<loc>(.*?)<\/loc>/g)].forEach((m) => console.log('  ' + m[1]));
}
